[VSSL-3982] Refactor Structure
vessl-ai/archived-images pull request #15
Opened 2023-01-03 05:08 UTC by NEM-NE

* Remove unnecessary file
* Change folder structure
* Update libraries version in dockerfile
* Update README

2023-01-03 06:00 UTC, Suckzoo commented on README.md
> +- `toruch` tags indicate torch version based on NGC
torch의 오타겠죠?

2023-01-03 06:01 UTC, Suckzoo commented on README.md
> +| 3.6    | x    | `python:3.6.14-slim-buster`          |
3.6 버립시다. 그리고 debian 기반 이미지 말고 더 가벼운 거 있을까요? (하는 김에)

2023-01-03 06:03 UTC, Suckzoo commented on README.md
> +### CPU - Worklad
base와 workload의 차이가 뭘까요?

2023-01-03 06:05 UTC, NEM-NE commented on README.md
> +- `toruch` tags indicate torch version based on NGC
수정했습니다 ㅎㅎ

2023-01-03 06:07 UTC, Suckzoo commented on README.md
> +vessl gpu image would be based on NGC's image. So if you want to find depenecy libraries then check the release note.
VESSL-supported GPU images are based on NVIDIA's NGC Image. You may want to check this site(link) to investigate what's inside.

2023-01-03 06:08 UTC, Suckzoo commented on README.md
> +vessl gpu image would be based on NGC's image. So if you want to find depenecy libraries then check the release note.
- torch (link)
- tf1 (link)
- tf2 (link)

2023-01-03 06:08 UTC, NEM-NE commented on README.md
> +### CPU - Worklad
base는 기본적인 툴과 데이터 사이언스 라이브러리를 설치하는 이미지입니다.
이전에는 base -> experiment -> workspace 순으로 이미지를 참조하면서 생성했습니다.

현재 구조로는 base -> workload(experiment + workspace) 순으로 이미지를 참조하면서 생성합니다.

2023-01-03 06:11 UTC, NEM-NE commented on README.md
> +vessl gpu image would be based on NGC's image. So if you want to find depenecy libraries then check the release note.
tf1과 tf2는 같은 페이지 내에서 작성되어 있기때문에 tensorflow로 통일하겠습니다.

2023-01-03 06:20 UTC, NEM-NE commented on README.md
> +| 3.6    | x    | `python:3.6.14-slim-buster`          |
그럼 alpine으로 변경하겠습니다!

2023-01-03 09:42 UTC, Suckzoo requested changes
마지막으로 slim-buster -> slim-bullseye 로 넘어가고 마칠까요? 데비안 릴리즈 목록을 보니 bullseye가 2021에 나왔고 이제 올라가도 될 거 같네요 :)

2023-01-03 09:46 UTC, NEM-NE commented
> 마지막으로 slim-buster -> slim-bullseye 로 넘어가고 마칠까요? 데비안 릴리즈 목록을 보니 bullseye가 2021에 나왔고 이제 올라가도 될 거 같네요 :)

변경사항 반영하겠습니다. 아직 GPU 환경 내에서 테스트 하지 못해서 내일 중으로 머지하겠습니다. @Suckzoo

2023-01-03 10:16 UTC, Suckzoo commented on README.md
> +| 3.6    | x    | `python:3.6.14-slim-buster`          |
slim으로 하되 debian 기반은 유지하기로 얘기했습니다

2023-01-04 05:34 UTC, Suckzoo approved these changes

2023-01-04 05:40 UTC, merged